---
title: "Wild git collaboration practice!"
author: "Taylor Medina & Erika Egg"
date: "1/25/2022"
output: html_document
---

```{r setup, include=TRUE, message = FALSE, warning = FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```

## STEP 5: No merge conflicts!

```{r partner 1}
### In this code chunk, start with the diamonds dataset (built in to
### ggplot2 package) and create a plot of price vs. carat (or some other
### variables of your choice)
ggplot(data = diamonds,
       aes(x = price, y = carat)) +
  geom_point(aes(color = cut))
 
```

```{r partner 2}
### In this code chunk, start with the diamonds dataset (built in to
### ggplot2 package) and create a subset based on filtering, e.g., 
### size greater than 1 carat or cut is "Ideal"
diamond_subset <- diamonds %>%
  filter(carat > 1 & cut == 'Ideal')

```

## STEP 7: Uh oh, merge conflicts!

```{r break-it-1}

### adding my own stuff - non-ideal subset, less than 1
diamond_subset <- diamonds %>%
  filter(carat < 1 & cut == 'Non-Ideal')

diamonds %>% 
  group_by(cut) %>% 
  summarize(mean_carat = mean(carat, na.rm = TRUE))
 
 #kept both of our codes!

```

## STEP 11: And even more merge conflicts!

```{r break-it-2}
### now subset exactly equal to 1
diamond_subset_another <- diamonds %>%
  filter(carat == 1)

